### ISSUE TITLE
VCP in buffer not updated (from device to PC)

### ISSUE THREAD

**Issue by TerribleKraal** [IntergatedCircuits/DebugDongleFW#2] opened 2018-07-23 14:55 UTC
I have an issue with the DebugDongle when used as a USB to USART bridge. I'm using it extensively and it never fails if the COM port (from the PC point of view) is never closed. But if we close the COM port there is a condition where the buffer sent back to the PC is in fact the previous one (as if the double buffer is not changing page, or changing 2 times ?).
Let me explain how you can replicate the issue: tie together UART Rx and UART Tx so everything is echoed back to the PC. Now I made a application which sends a random number of bytes between 2 to 64 every 100ms and verifies that the received content is the same as what we sent. As said earlier if the COM port is never closed then the application never fails.
Now whenever the number of bytes is equal to 25 (arbitrary can be anything) I choose to close the COM port, wait 100ms, open it again, wait 200ms and start again to send random number of bytes. In some cases the dongle will eventually fail and always send the same buffer (albeit the number of bytes being right).

**Comment by benedekkupper** [comment] 2018-07-23 15:44
Could you check if adding `USART_vDeinit(vcp_uart);` to line 141 of vcp_if.c has any effect on this problem?

**Comment by TerribleKraal** [comment] 2018-07-24 13:06
Hi, I tried that and it did not help.
Furthermore, if I send 1 byte X, close the port, wait 1 second, open the port, wait 1 second -> ~~all subsequent~~ next transfer will fail with the 1st byte being X and the rest being 0 (I say the rest because it sends back the same number of bytes it received).

Edited: really only the first transfer following the re-opening of the port is wrong then if the port is not closed all transfers are good.

**Comment by benedekkupper** [comment] 2018-07-26 13:11
One more question, was the incorrect data received on the host before the port was closed (meaning that you receive it once before closing and once after reopening)?

**Comment by TerribleKraal** [comment] 2018-07-26 13:21
Hi, thank you for taking time to look into it.

The incorrect data is received only after reopening, not before closing.

**Comment by benedekkupper** [comment] 2018-07-27 11:31
What I see as the most probable root cause is that the endpoint packet is prepared in the device peripheral, but isn't read by the host until after the reopening of the port. So the new setting of TX_COUNT register applies, but the previously loaded data isn't cleared. A possible solution could be to set TX_COUNT to 0 when the line config is set, but I can't promise any deadline for actually checking it (it's summertime after all :) ).

**Comment by TerribleKraal** [comment] 2018-07-27 11:45
No problems.
In the meantime as I know that the first packet will be wrong I can initiate a dummy read on the COM port and discard the answer.

Enjoy the summertime :-)

**Comment by benedekkupper** [comment] 2018-08-05 21:30
I pushed updates to USBDevice and DebugDongle: CDC has a more sensible application interface for the majority use case (serial ports). The data interface is closed and reopened when the line coding parameters are set. This should resolve this issue, however I haven't tested it yet. If the set line coding message isn't sent by the host every time the port is opened then there is no way to fix this on the device side alone.

**Comment by benedekkupper** [comment] 2018-08-24 18:01
I'm closing this as it's either solved by the API change or the host doesn't resend line config when reconnecting, in which case the problem cannot be solved on the device side.

**Closed as completed by benedekkupper** 2018-08-24 18:01 UTC
Labels: bug
